config/routes.rb
Rails.application.routes.draw do
  resources :goals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  get '/welcome' => 'welcome#index'

  get 'signup' => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/timer' => 'records#new'
  post 'timer' => 'records#create'

  get '/stats' => 'records#index'
  get '/stats/year' => 'records#index'
  get '/stats/month' => 'records#index'
  get '/stats/week' => 'records#index'
  get '/stats/day' => 'records#index'
  resources :records

  get '/achievements' => 'achievements#index'

  get '/goals' => 'goals#index'

end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.where(uname: current_user.uname)
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to '/goals', notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:uname, :title, :category, :description)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<h4 style="font-family: 'Varela Round', sans-serif; color: white;">Add a New Goal</h4>
<div align="left" style="width: 50%;" class="form-wrapper">
  <%= form_with(model: goal, local: true) do |form| %>
    <% if goal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>
  
        <ul>
          <% goal.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form.hidden_field :uname, :value => current_user.uname %>
  
    <div class="field">
      <%= form.text_field :title, :placeholder => "title of goal here" %>
    </div>
  
    <div class="field">
      <%= form.text_field :category, :placeholder => "category of goal here" %>
    </div>
  
    <div class="field">
      <%= form.text_area :description, :placeholder => "description of goal here" %>
    </div>
  
    <div class="actions">
      <%= form.submit "confirm", class: 'reg-submit' %>
    </div>
  <% end %>
</div>

app/views/goals/destroy.js.erb
$('.del-btn').bind('ajax:success', function() {
    $(this).closest('div').fadeOut();
});

app/views/goals/index.html.erb
<div class='container mt-5'>
  <h1 style="font-size: 75px; font-family: 'Indie Flower', cursive; color: white; text-align: center;">
    <strong>myTimer</strong> <%= icon('far', 'clock', class: 'strong') %>
  </h1> 

  <br><br>

  <h3 style="font-family: 'Varela Round', sans-serif; color: white; text-align: center;">
      <%= current_user.uname %>'s goals
  </h3>

  <div class="row">
    <div class="col-2">

    </div>
    <div class="col-8">
      <hr>
      <div align="center" id='new-goal'>
        <%= link_to 'Create New Goal', new_goal_path, class: "btn btn-primary", remote: true %>
      </div>
      <hr>
      <% @goals.each do |goal| %>
        <div class="goal-wrapper" align="center">
          <div class="row">
            <div class="col" align="left">
              <h2><strong><u><%= goal.title %></u></strong></h2>
            </div>
            <div class="col" align="right">
              <button class="option-btn" type="button" data-toggle="collapse" data-target="#collapse<%= goal.id %>" aria-expanded="false" aria-controls="collapse<%= goal.id %>">
                Show/Collapse Info
              </button>
            </div>
          </div>
          
          <div class="collapse" id="collapse<%= goal.id %>">
            <hr>
            <p><strong><u>Category:&nbsp;</u></strong><%= goal.category %></p>
            <p><strong><u>Description:&nbsp;</u></strong><%= goal.description %></p>

            <div class="row">
              <div class="col" align="center">
                <%= link_to 'Destroy Goal', goal, method: :delete, class: "btn btn-danger" %>
              </div>
            </div>

          </div>

        </div>
        <br>
        
      <% end %>
      
    </div>
    <div class="col-2">

    </div>
  </div>

  <div align='center' id="exit-link">
    <a href='/welcome' style='color:black;'>&larr; go back to home page.</a>
  </div>
</div>

app/views/goals/new.html.erb
<div class="container mt-5">
    <h1 class='start-label'>set a new goal.</h1>
    <div class='row'>
        <div class='col'>
            <div class='alert login-form-wrapper'>
                <%= render 'form', goal: @goal %>
            </div>
        </div>
        <div class='col'>
            
        </div>
    </div>

    <a href='/goals' style='color:black;'>&larr; go back to goals page.</a>
</div>

app/views/goals/new.js.erb
var form = $("<%= j render 'form', goal: @goal %>")
form.appendTo($('#new-goal a').hide().parent()).fadeIn(2000)